### ISSUE TITLE
CF Issue - No files show on new CF site

### ISSUE THREAD

**Issue by brisingraerowing** [ThePoleThatFishes/NC-Extra-Ingot-Blocks#6]
**Describe the bug**
For some reason, no files show on the new CF site, but do show on the legacy site.

**Expected behavior**
Files show on new CF

**Screenshots**
![image](https://github.com/ThePoleThatFishes/NCO-script-addons/assets/250409/a61e4895-9995-4b15-aa4d-14e0d797c44a)

**Addon version:**
N/A (CF Issue)

**Additional context**
Probably need to contact CF about this.

**Comment by ThePoleThatFishes** [comment]
Thank you for the report, I have made a ticket to CF and I'm waiting on a response.

**Comment by brisingraerowing** [comment]
I've found several projects with this issue, FWIW. The new site has all sorts of weird bugs. At least the legacy site works.

**Comment by ThePoleThatFishes** [comment]
I have received a response from CF:

> Thank you very much for contacting us, I will do my best to assist you with CurseForge :)
After investigation this seems like a cache issue due to the project not being updated for a long time.
​We're invalidating the project cache on our end which should solve this issue. Please check again in ~1 hour and let us know if it still isn't working

It was indeed due to the project not being updated in two years! On my end, the files are there now on the new site, please follow up with whether the files are there on your end as well.

**Comment by brisingraerowing** [comment]
They show up here as well.
